name: Test on Merge
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test_typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: "typescript"
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run build
  test_go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: "golang"
          cache: true
      - run: go test ./...
  test_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache-dependency-path: "python"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --use-pep517
          pip install build
      - run: pytest
      - run: python -m build
  test_hsp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hsp
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenHSP
        uses: BonyChops/setup-openhsp@v1.0.0
      - name: Generate Test
        run: ./generate_testcases.sh
      - name: Build Test
        run: hspcmp -d -i -u ./misezan_test.hsp -o./misezan_test.ax
      - name: Run Test
        run: hsp3cl ./misezan_test.ax
