name: Test for Every Language on PR
"on": pull_request

jobs:
  test_typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: "typescript"
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run build
  test_go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: "golang"
          cache: true
      - run: go test ./...
  test_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache-dependency-path: "python"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --use-pep517
          pip install build
      - run: pytest
      - run: python -m build
  test_hsp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hsp
    steps:
      - uses: actions/checkout@v4
      - name: Cache HSP
        id: cache_hsp
        uses: actions/cache@v3
        with:
          path: |
            OpenHSP-3.6
          key: "hsp-v3.6"

      - name: Download
        if: steps.cache_hsp.outputs.cache-hit != 'true'
        run: curl -L https://github.com/onitama/OpenHSP/archive/refs/tags/v3.6.tar.gz -o hsp.tar.gz
      - name: Extract
        if: steps.cache_hsp.outputs.cache-hit != 'true'
        run: tar -zxvf hsp.tar.gz
      - name: Build hspcmp
        if: steps.cache_hsp.outputs.cache-hit != 'true'
        run: make hspcmp
        working-directory: hsp/OpenHSP-3.6
      - name: Build hsp3cl
        if: steps.cache_hsp.outputs.cache-hit != 'true'
        run: make hsp3cl
        working-directory: hsp/OpenHSP-3.6
      - name: Generate Test
        run: ./generate_testcases.sh
      - name: Build Test
        run: ./OpenHSP-3.6/hspcmp -d -i -u ./misezan_test.hsp -o./misezan_test.ax
      - name: Run Test
        run: ./OpenHSP-3.6/hsp3cl ./misezan_test.ax
